version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run: pip install black
      - run: black . --check
      - run: sudo python setup.py install
      - run: echo $service_acct_json > "service_acct.json"
      - run: test -f service_acct.json
      - run: pytest .

workflows:
  main:
    jobs:
      - build-and-test
